-- +module nostr
-- RETIRED. The vertex_scores and vertex_search_cache tables declared here
-- moved to the Vertex DVM plugin (internal/vertex/plugin.go CacheDDL), which
-- the dvm registry applies at migrate time and the schema reconciler treats
-- as part of the desired schema. Kept as an empty ledger entry so the
-- migration history stays contiguous.
