-- RETIRED. The one-time like/repost historical backfill this file performed
-- is now generic: when the registry (internal/rules) creates a rule's
-- aggregate table for the first time, Migrate backfills it from raw history
-- automatically (see Store.applyGeneratedSchema). Kept as an empty ledger
-- entry so the migration history stays contiguous.
