-- +module core
-- RETIRED. This migration bounded ClickHouse's self-logging with
-- ALTER TABLE system.<log> MODIFY TTL, and that approach is now known to be
-- wrong: MODIFY TTL changes the table's structure, so the next server restart
-- found a mismatch, renamed the table to `<name>_0` and created a fresh
-- TTL-less one. The 20 GB it was meant to reclaim was orphaned instead, and the
-- volume GREW 45.88 -> 52.47 GB. Migrations 024 and 025 cleaned that up.
--
-- The policy now lives where it belongs, in ClickHouse config:
-- deploy/clickhouse/system-logs.xml declares the TTLs and removes the pure-noise
-- logs outright. Declaring it there means the config and the table agree, so
-- there is no rename and no orphan — see that file's header, and 024's.
--
-- Retiring the statements (rather than deleting the file) matters for a FRESH
-- database. Every table this migration ALTERed is either removed by that config
-- (text_log, processors_profile_log, query_views_log) or not yet materialized
-- on a new server, and ClickHouse has no ALTER TABLE IF EXISTS — so re-running
-- these statements fails the very first deploy of any new nagg service. The
-- deployments that already applied this file keep their ledger row; nothing
-- re-runs.
